# Generated by Django 4.1.7 on 2023-03-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0002_alter_aemter_options_alter_maijahr_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maijahr',
            options={'ordering': ['jahr'], 'verbose_name_plural': 'Maijahre'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['nachname', 'vorname'], 'verbose_name_plural': 'Personen'},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='nachname_heirat',
            new_name='suchnamen',
        ),
        migrations.AlterField(
            model_name='aemter',
            name='amt',
            field=models.CharField(choices=[('MK', 'Maikönig'), ('MN', 'Maikönigin'), ('VS', 'Vorsitzender'), ('VS2', '2. Vorsitzender'), ('SF1', '1. Schriftführer'), ('SF2', '2. Schriftführer'), ('SF3', '3. Schriftführer'), ('KS1', '1. Kassierer'), ('KS2', '2. Kassierer'), ('KS3', '3. Kassierer'), ('MH', 'Maihauptmann'), ('SPEV', 'Sonderposten EV'), ('EPEV', 'Ehrenposten EV'), ('VD', 'Vorstand'), ('RT', 'Reiter'), ('HR', 'Hauptremmel'), ('MR', 'Mairemmel'), ('BT', 'Baumträger'), ('CT', 'Cheftechniker'), ('TR', 'Techniker')], max_length=8),
        ),
    ]
